### ISSUE TITLE
InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by Heartz66** [liamcurry/passport-steam#48] opened 2016-12-06 19:20 UTC
Steam is very slow last time, even when connecting Steam client can take upto 25 seconds and loading inventory sometimes result in a ETIMEDOUT.

Changed my IP and DNS.
Receiving the following errors:

- Failed to verify assertion
- Failed to discover OP endpoint URL

Node version: 4.6.2
Using latest passport-steam version.

I am using the following code:

`app.get("/login", passport.authenticate("steam", {failureRedirect: "/"}), () => {});`

`app.get("/login/return", (req, res, next) => {
    req.url = req.originalUrl;
    next();
}, passport.authenticate("steam", {
    failureRedirect: "/"
}), (req, res) => {
    res.redirect("/");
});`

**Comment by mnzt** [comment] 2016-12-08 10:38
duplicate of https://github.com/liamcurry/passport-steam/issues/37

**Closed by mnzt** 2016-12-08 10:38 UTC
