### ISSUE TITLE
Steamcommunity changed all http to https

### ISSUE THREAD

**Issue by snax4a** [liamcurry/passport-steam#81] opened 2018-04-06 15:12 UTC
Since Valve switched everything on steamcommunity.com to https, a great many websites using Steam OpenID are now giving errors when you try to log in.

The reason is because with Valve's recent SSL/TLS switch, OpenID URLs were changed too. That means while websites used to identify you by http://steamcommunity.com/profiles/{number} they are now receiving https://steamcommunity.com/profiles/{number} back from Valve instead. With this unexpected change, websites generally aren't coded to handle it and will throw an authentication error.

**Comment by snax4a** [comment] 2018-04-06 15:35
I updated it to v1.0.9 but im still unable to login, there are no errors

**Comment by lukealford** [comment] 2018-04-07 03:27
line 88 on the `strategy.js` needs updating as well. 

from `var identifierRegex = /^http:\/\/steamcommunity\.com\/openid\/id\/(\d+)$/;`
to `var identifierRegex = /^https:\/\/steamcommunity\.com\/openid\/id\/(\d+)$/;`

**Comment by coooool123** [comment] 2018-04-07 03:37
I've updated mine too but still can't login...

**Comment by snax4a** [comment] 2018-04-07 05:10
luke this line was updated in v1.0.9 but still its not fixed

**Comment by lukealford** [comment] 2018-04-07 05:33
Do you have `?` try removing that as that's all I changed and it all started working normal for me, I was also having the same problem on a nginx proxy removal of the `?` solved this for me.

`/^https?:\/\/steamcommunity\.com\/openid\/id\/(\d+)$/;`

vs 

`/^https:\/\/steamcommunity\.com\/openid\/id\/(\d+)$/;`

**Comment by snax4a** [comment] 2018-04-07 05:44
What is your proxy configuration? You use 1.0.9 and Just removed ? After
https on line 88?


W dniu sob., 7.04.2018 o 07:33 Luke Alford <notifications@github.com>
napisał(a):

**Comment by lukealford** [comment] 2018-04-07 05:55
> What is your proxy configuration?

Just a normal nginx proxy passing to the express port. 

> You use 1.0.9 and Just removed ? After https on line 88?

I manually updated each of `http` lines before 1.0.9 was released, the only real difference from 1.0.9  and my version is the `?` on line 88. I hope this helps.

**Comment by snax4a** [comment] 2018-04-07 11:13
Can you give me your skype or steam? We will try to fix it together i will
pay :)


W dniu sob., 7.04.2018 o 07:55 Luke Alford <notifications@github.com>
napisał(a):

**Comment by mnzt** [comment] 2018-04-07 17:09
Closing as not an issue of the package.

**Closed by mnzt** 2018-04-07 17:09 UTC

**Comment by snax4a** [comment] 2018-04-07 17:11
But it is issue of package Becouse it worked before update


W dniu sob., 7.04.2018 o 19:10 Toby Archer <notifications@github.com>
napisał(a):

**Comment by mnzt** [comment] 2018-04-07 17:12
The issue is you not configuring your webserver with SSL correctly, not how passport-steam functions

**Comment by snax4a** [comment] 2018-04-07 17:13
So with this update website must have SSL set up to work with paszport
steam? I was using this package without SSL before


W dniu sob., 7.04.2018 o 19:12 Toby Archer <notifications@github.com>
napisał(a):
