### ISSUE TITLE
InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by graycatfromspace** [liamcurry/passport-steam#13] opened 2015-06-10 15:27 UTC
InternalOpenIDError: Failed to verify assertion
    at /var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36
    at /var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1068:12
    at /var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1192:16
    at /var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1310:16
    at done (/var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:318:9)
    at IncomingMessage.<anonymous> (/var/www/csgobig.com/express/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:322:32)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Im getting this error randomly and I cant seem to find the cause...

**Comment by graycatfromspace** [comment] 2015-06-10 15:55
on further investigation seems to be related to this.

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(obj, done) {
  done(null, obj);
});

**Comment by graycatfromspace** [comment] 2015-06-12 20:24
seems related to a fucked up response from steam..

**Comment by BenjaminNeilDavis** [comment] 2015-07-28 04:49
I am having the same issue @graycatfromspace Any luck?

**Comment by DeltaMeter** [comment] 2015-08-01 01:05
@BenjaminNeilDavis I had the problem because I was using the same API key twice, once on my prod machine and once on my dev machine.

**Comment by FelikZ** [comment] 2015-08-15 10:52
Fixed by adding missing middleware:

```javascript
  app.use(passport.initialize());
  app.use(passport.session());
```

**Comment by meitinglei** [comment] 2015-08-17 05:57
i have the same issue，can't fixed it

**Comment by FelikZ** [comment] 2015-08-17 14:41
@meitinglei try to use passport middleware AFTER all other express middlewares.

**Comment by luop90** [comment] 2015-12-06 23:47
This issue is still occurring. It seems to happen at random, because some times users can login, and other times they can't.

**Comment by mnzt** [comment] 2016-01-19 10:50
@luop90 are you still having this issue?

**Comment by aidenwallis** [comment] 2016-01-22 22:42
I found out what the issue is, there's something wrong with a dependency inside, passport-openid, downgrade it and place it inside the passport-steam and it should fix it! :)

**Comment by luop90** [comment] 2016-01-23 01:54
@mnzt Yes. In fact, it got so bad, I switched to express because I couldn't get this one to work more then 10% of the time.

**Comment by mnzt** [comment] 2016-01-23 12:35
@luop90 express js irrelevant to this. Closing.

**Closed by mnzt** 2016-01-23 12:35 UTC
Labels: bug

**Comment by luop90** [comment] 2016-01-23 14:17
I edited my comment to everyauth, "express" was a typo... W/e

**Comment by aidenwallis** [comment] 2016-01-23 18:38
I found the issue, I got mine to work finally, it doesn't seem as if you can use a database with it. As weird as it sounds, I just store a class in cookies in a MongoStore now, as it seems to work great now. And use the same passport and passport-steam version as in the example site. It all works great for me now! I'm not too fussed about storing it in a cookie, as it's not accessible to the user and the cookie is httpOnly and secure

**Comment by mnzt** [comment] 2016-01-23 20:02
@aidenwallis I've personally used this package with a database, what you do with the data shouldn't cause an error with the package at all, just an error with how you're handling it.

**Comment by aidenwallis** [comment] 2016-01-23 20:05
I don't know, all I know is when I stopped it from adding users to a database everything works great. But it's not too big of a worry with my site so I'm just going to keep it this way, I literally just manipulated the example to use mongoose with no luck, so after using no database it seems to work.

**Comment by mnzt** [comment] 2016-01-23 20:56
@aidenwallis certainly sounds like a problem external to passport-steam. 

At least you've got something to work out for you :).
